### ISSUE TITLE
Simulations on Tags?

### ISSUE THREAD

**Issue by ghost** [giovannihenriksen/Anki-Simulator#31]
Hi. I use a combined deck and hierarchical tags to organize my collection. Would it be possible to add simulation based on tags?

**Comment by giovannihenriksen** [comment]
Thanks for the suggestion! While I think this could be useful, I think it could compromise some of the simplicity that makes the add-on intuitive to use (I'm a reluctant to increase the number of textfields that could cause confusion). I'll keep the suggestion in mind. For now the work around would be to temporarily transfer those cards to another deck to simulate with.

**Comment by Cupbox** [comment]
Thanks. I'll do that.
