### ISSUE TITLE
Number of cards?

### ISSUE THREAD

**Issue by cjdduarte** [giovannihenriksen/Anki-Simulator#32]
is this information "Number of cards" or "Number of cards / day"?

![image](https://user-images.githubusercontent.com/42243532/78432543-d5cf9f80-764b-11ea-8916-8586faa492fd.png)

**Comment by giovannihenriksen** [comment]
It shows the total number of repetitions for a given day.

**Comment by cjdduarte** [comment]
Suggestion: rename for "Number of cards / day"

**Comment by giovannihenriksen** [comment]
> Suggestion: rename for "Number of cards / day"

Would that make sense though? Then the whole chart would read number of cards/day/day

I'm considering changing the text to 'Number of repetitions' instead
