### ISSUE TITLE
Graph background is white on alternate Anki builds when night mode is active 

### ISSUE THREAD

**Issue by theghsurgeon** [giovannihenriksen/Anki-Simulator#36]
Anki 2.1.28 (7d8818f8) Python 3.8.1 Qt 5.9.7 PyQt 5.13.2
    Platform: Mac 10.15.6
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-07-18 18:24:14
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2020-04-22T18:45, 'None', '']
    Anki Simulator ['817108664', 2020-05-25T05:05, 'None', '']
    Anki Zoom ['538879081', 2020-04-03T20:20, 'v1.1.3', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2020-07-07T19:44, 'None', '']
    Clickable Tags v20 Anki 2120 support ['1739176371', 2020-03-13T10:25, 'None', '']
    Countdown To Events  Exams ['1143540799', 2020-07-17T09:07, 'None', '']
    Customize Sidebar ['1988760596', 2020-01-15T16:01, 'None', '']
    Edit Field During Review Cloze ['385888438', 2020-06-11T08:32, 'None', '']
    Extended Card Stats During Review ['1008566916', 2017-08-29T14:59, 'None', '']
    Fastbar- with nightmode support ['46611790', 2020-03-20T10:34, 'None', '']
    Hierarchical Tags 2 ['594329229', 2020-04-11T12:36, 'None', '']
    High Yield Tags ['1918380616', 2020-06-30T16:35, 'None', '']
    Improved Quizlet to Anki 21 Importer ['538351043', 2020-05-18T10:45, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2020-01-11T19:33, 'None', '']
    More Answer Buttons for New Cards ['more_answer_buttons', 0, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2020-03-31T16:19, 'None', '']
    More Overview Stats ['2116130837', 2020-02-17T11:01, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-03-23T13:32, 'None', '']
    Puppy Reinforcement ['puppy_reinforcer', 0, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T09:23, 'None', '']
    Set Font Size ['651521808', 2018-09-30T07:23, 'None', mod]
    Special Fields ['1102281552', 2020-07-06T14:03, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T05:11, 'None', '']
    Symbols ['1461102936', 2019-04-18T16:21, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-04-17T18:33, 'None', '']
    True Retention by Card Maturity ['923360400', 2017-08-29T15:00, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2020-04-17T08:22, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2020-05-08T09:16, 'None', '']
    put ALL due learning cards first modified v2 support ['1807121582', 2019-11-24T14:20, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1008566916 1046608507 1102281552 1143540799 1461102936 153625306 1556734708 1739176371 1807121582 1918380616 1949865265 1988760596 2116130837 374005964 385888438 46611790 538351043 538879081 561945101 594329229 651521808 817108664 831846358 864545277 874215009 923360400
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by giovannihenriksen** [comment]
I'm assuming that a bug occurred? I can't see out what went wrong just from your add-on list ;p

**Comment by glutanimate** [comment]
@giovannihenriksen Sorry about the confusion. I directed @theghsurgeon here. They're experiencing an issue where the graph view will not use the proper settings for night mode.

@theghsurgeon is it OK if I edit your report with the screenshot you sent me? (you can also add the screenshot yourself of course)

**Comment by theghsurgeon** [comment]
The graph won't display in night mode.
![Screen Shot 2020-07-19 at 1 25 56 PM](https://user-images.githubusercontent.com/68513316/87884718-61442500-c9de-11ea-8ac9-2911046f19c9.png)

**Comment by glutanimate** [comment]
@giovannihenriksen 

Alright, I think I have tracked this down. It looks like the background color we apply when night mode is active does not work on alternate Anki builds for whatever reason (i.e. builds with older Qt and QtWebEngine libs). I've submitted a PR in #38 that addresses this by making our CSS conditional to the Anki build used.

@theghsurgeon 

Thanks again for the debug info and screenshot. These were very helpful in tracking this down. It looks like you are using the alternate version of Anki which doesn't work as well with the add-on. Is there any particular reason you went with that version? Since you're using an up-to-date version of macOS, I'd highly recommend going with the standard Anki build. That should immediately fix the background issue with Anki Simulator, but also improve the compatibility of your Anki installation with many other add-ons. You can download the standard build here (it's the top-most blue button under "Download Anki"): https://apps.ankiweb.net/#download

If you do need to use the alternate build, the next update to Anki Simulator should fix the background issue there as well. But I'd still highly recommend going with the standard build to avoid other issues in the future.

**Comment by theghsurgeon** [comment]
I play around softwares a lot, I like to see the new features it got. I was impressed by what i read that's the reason i wanted to try it out. I will take your recommendation. @giovannihenriksen

**Comment by glutanimate** [comment]
@theghsurgeon Sorry, I think there might be a small misunderstanding here. There's no harm installing the latest version of Anki (2.1.28), it's just that it looks like you probably picked the alternate version by accident. Anki releases always come in two versions, a standard version (e.g. 2.1.28-standard, blue button on the download page) and an alternate version (e.g. 2.1.28-alternate, white button on the download page). I would recommend always going with the standard version if nothing prohibits you from using it. The alternate version is only there for older PCs and Macs that can't run the latest operating systems.

Hope that clarifies things!

**Comment by theghsurgeon** [comment]
oh wow, never new this. Thanks for the clarification. It works i just tried simulating and i have the stable version now.

**Comment by theghsurgeon** [comment]
Hey @glutanimate What's with progress bar ? is there a version for the new anki release yet?
![Screen Shot 2020-07-20 at 5 11 11 PM](https://user-images.githubusercontent.com/68513316/87987097-0ed13a00-caac-11ea-894b-11c9fe2dd487.png)

**Comment by glutanimate** [comment]
Not yet, but I'm working on it. It can be difficult to keep up with these updates as every one breaks one add-on or another. If you use a lot of add-ons, the best approach likely is to stay on a an older version of Anki for a while before upgrading. 2.1.23 is fairly good as far as add-on compatibility is concerned.

**Comment by theghsurgeon** [comment]
Thanks for letting me know.
