### ISSUE TITLE
Decimal learning/lapse steps error

### ISSUE THREAD

**Issue by JoelMahon** [giovannihenriksen/Anki-Simulator#41]
My first step is 0.5 for both learning and lapses, which is a legal value that works fine with Anki, however this addon forces me to change it to 1 to make it work.

This isn't a big issue and probably will never be dealt with (maybe I'll take a look if work hasn't blown me out by next weekend), and I doubt the values actually matter, especially with a 30 second difference, just thought it was worth mentioning, if anything the biggest problem was working out what was wrong from the error pop up.

Thanks for this great addon though.

**Comment by giovannihenriksen** [comment]
Thanks for reporting this! I'll keep it in mind for the next update
