### ISSUE TITLE
Idea/Update/Bug : Accept decimals in learning steps

### ISSUE THREAD

**Issue by Cashburner** [giovannihenriksen/Anki-Simulator#50]
I use 0.5 10 as learning steps, since I think I remember and learn stuff better in 30secs than in 1minute since a lot of new cards pile up.
It seems the addon does not work with decimals. It would be awesome to see this in future updates. Thanks!

**Comment by giovannihenriksen** [comment]
Fixed! Will push the update to Ankiweb soon
