### ISSUE TITLE
Can't use valid steps

### ISSUE THREAD

**Issue by kanjieater** [giovannihenriksen/Anki-Simulator#54]
Anki supports fractions of minutes for steps, like the following: 0.16 0.32 0.64 5 600 (10s, 20s, 30s, 5min, 10hr). When I load my deck with these steps, I get the following error:

![image](https://user-images.githubusercontent.com/32607317/113295969-7fc52480-92be-11eb-8fe5-defd9ebfdf20.png)

**Comment by giovannihenriksen** [comment]
Which version of Anki Simulator are you on? This was supposed to be fixed in an earlier update

**Comment by kanjieater** [comment]
an old version! sorry.

**Comment by giovannihenriksen** [comment]
No problem.
