### ISSUE TITLE
Doesn't seem to be calculating new cards correctly?

### ISSUE THREAD

**Issue by fjaieohfaufn** [giovannihenriksen/Anki-Simulator#61]
I have only 1 learning step, for 1 day. If I add 5 new cards each day, I should ALWAYS have at least 10 cards to review (5 today and 5 graduated from yesterday). However, in the simulation in the attached screenshot, it is mostly showing < 10 reviews expected and even frequently dipping below 5. Is something wrong with my settings, or is Anki Simulator not calculating something correctly?

![image](https://user-images.githubusercontent.com/86940684/129516657-41a3d3cc-a316-4249-b143-c71d5cd0ff56.png)

**Comment by giovannihenriksen** [comment]
Hi, are there sufficient unseen cards in this deck? If not, does the problem persist if you check 'simulate additional new cards'?

**Comment by fjaieohfaufn** [comment]
Thanks for your response! I'm not sure what you mean by "sufficient unseen cards". That deck currently has 358 cards, none are suspended.

The below screenshot shows simulation 1 (same settings as original screenshot above, still dips below 5) and simulation 2 has 1000 "simulate additional new cards" checked.

I also use auto ease factor, but I don't imagine that should throw this off.

![image](https://user-images.githubusercontent.com/86940684/129644378-728bfde2-2fd2-4ae2-b56d-c01e63080ec0.png)

**Comment by fjaieohfaufn** [comment]
I believe I now understand what you were referring to with "sufficient unseen cards in this deck". No, I did not have new cards stockpiled, I generally add them daily. I now understand I need to keep the "Simulate (additional) new cards" checked.
